export const INDIVIDUAL_PROJECT_STATES = {
  IDEA: 'IDEA',
  PLANNING: 'PLANNING',
  DEVELOPMENT: 'DEVELOPMENT',
  DOCUMENTATION: 'DOCUMENTATION',
  GITHUB_SUBMISSION: 'GITHUB_SUBMISSION',
  VERIFICATION: 'VERIFICATION',
  MODIFICATION_REQUESTED: 'MODIFICATION_REQUESTED',
  RESUBMISSION: 'RESUBMISSION',
  FINAL_VERIFICATION: 'FINAL_VERIFICATION',
  COMPLETED: 'COMPLETED'
};

export const GROUP_PROJECT_PHASES = {
  IDEATION: 'IDEATION',
  PLANNING_DESIGN: 'PLANNING_DESIGN',
  DEVELOPMENT: 'DEVELOPMENT',
  SUBMISSION: 'SUBMISSION',
  REVIEW: 'REVIEW',
  MODIFICATION: 'MODIFICATION',
  FINAL_VERIFICATION: 'FINAL_VERIFICATION',
  COMPLETED: 'COMPLETED'
};

export const REQUIREMENT_STATUSES = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED',
  MODIFICATION_REQUIRED: 'MODIFICATION_REQUIRED'
};

export const FUNCTIONALITY_TEST_STATUSES = {
  PASS: 'PASS',
  FAIL: 'FAIL',
  BLOCKED: 'BLOCKED',
  NOT_TESTED: 'NOT_TESTED'
};

export const MODIFICATION_STATUSES = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED'
};

export const ATTENTION_SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};
